## Linear Algebra with Python and Sympy

#### Commands in Jupyter Notebook
- Cells have two main modes: code and markdown, can switch from drop down menu above
- To execute a code cell you can push Run button from menu above or use Shift+Enter
- Can insert new cell above/below using the insert button above

SymPy is a Python module for performing symbolic computations. This notebook explain how use it to perform linear algebra computations.

Execute this cell to load SymPy:

In [1]:
#load SymPy module content
from sympy import *

#this makes printouts of matrices and vectors more readeable:
init_printing(use_latex='mathjax')

### Constructions of matrices
The simplest way to create a matrix is to lists its elements. Matrices are entered row by row. Each row must be enclosed in square brackets, and then the whole collection of rows is again enclosed in square brackets:

In [2]:
A = Matrix([[1, 2, 3], [4, 5, 6], [7,8,9]])
A #this displays the matrix

⎡1  2  3⎤
⎢       ⎥
⎢4  5  6⎥
⎢       ⎥
⎣7  8  9⎦

In [3]:
B = Matrix([[1,2,4]])
B

[1  2  4]

In [4]:
v = Matrix([-2,0,4])
v

⎡-2⎤
⎢  ⎥
⎢0 ⎥
⎢  ⎥
⎣4 ⎦

## Entering Fractions
Because of the way fractions are stored digitally, for precise computation we need to ensure that Python knows we are referring the exact fraction, not an approximation of it. 

In [5]:
F1 = Matrix([[1/7 , -1],[0, -1/3]])
F1

⎡0.142857142857143          -1        ⎤
⎢                                     ⎥
⎣        0          -0.333333333333333⎦

As you can see, the fractions are expanded as decimals and truncated. While this may seem 'good enough', we will see that this can potentially cause major issues.

In [6]:
F2 = Matrix([[Rational(1,7), -1],[0,Rational(-1,3)]])
F2

⎡1/7   -1 ⎤
⎢         ⎥
⎣ 0   -1/3⎦

### Matrices of 0's and 1's

We often will construct matrices that mostly comprised of 0's and 1's (or just initialize them), so here are some ways to create them.

In [7]:
Z = zeros(4,3)
Z

⎡0  0  0⎤
⎢       ⎥
⎢0  0  0⎥
⎢       ⎥
⎢0  0  0⎥
⎢       ⎥
⎣0  0  0⎦

In [8]:
One_Matrix = ones(2,4)
One_Matrix

⎡1  1  1  1⎤
⎢          ⎥
⎣1  1  1  1⎦

### Diagonal Matrices
Diagonal matrices are also of great importance (even though we may not have encountered them much yet.)

In [9]:
D = diag(1, 2, 3, -3)
D

⎡1  0  0  0 ⎤
⎢           ⎥
⎢0  2  0  0 ⎥
⎢           ⎥
⎢0  0  3  0 ⎥
⎢           ⎥
⎣0  0  0  -3⎦

In [10]:
I = eye(4) # 4x4 identity matrix
I

⎡1  0  0  0⎤
⎢          ⎥
⎢0  1  0  0⎥
⎢          ⎥
⎢0  0  1  0⎥
⎢          ⎥
⎣0  0  0  1⎦

### Matrices from Lists

A list is a basic structure in Python. It's quite literally what the name implies: a list

In [11]:
#create a list of elements
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
a

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

In [12]:
#reshape the list into a 3x4 matrix
A = Matrix(a).reshape(3, 4)
A

⎡1  2   3   4 ⎤
⎢             ⎥
⎢5  6   7   8 ⎥
⎢             ⎥
⎣9  10  11  12⎦

In [13]:
B = Matrix(a).reshape(6,2)
B

⎡1   2 ⎤
⎢      ⎥
⎢3   4 ⎥
⎢      ⎥
⎢5   6 ⎥
⎢      ⎥
⎢7   8 ⎥
⎢      ⎥
⎢9   10⎥
⎢      ⎥
⎣11  12⎦

$\textbf{Note 1.}$ Reshaping works only if the number of elements of the list is exactly equal to the number of entries of a matrix of specified dimensions.

$\textbf{Note 2.}$ Reshaping makes consecutive chunks of a list into rows of a matrix. In order for such chunks to become columns of a matrix, we can apply transpose of a matrix, which makes rows into columns:

In [14]:
A2 = A.T  #takes the transpose of the matrix A 
A2

⎡1  5  9 ⎤
⎢        ⎥
⎢2  6  10⎥
⎢        ⎥
⎢3  7  11⎥
⎢        ⎥
⎣4  8  12⎦

### Acessing elements, rows, and vectors of a matrix

We can access elements of a matrix by specifying the row and column of the element.

Note. In Python indexing starts with 0. Thus, the first row of a matrix has index 0, the second row has index 1 and so on.

In [15]:
A = Matrix([[1, 2, 3], [4, 5, 6], [7,8,9]])
A

⎡1  2  3⎤
⎢       ⎥
⎢4  5  6⎥
⎢       ⎥
⎣7  8  9⎦

In [16]:
A[1,0]

4

Can also modify elements of an existing matrix this way.

In [17]:
A[1,1] = 10
A

⎡1  2   3⎤
⎢        ⎥
⎢4  10  6⎥
⎢        ⎥
⎣7  8   9⎦

To access a row: we use ':' in place of the second index. (Grabs all things from the second index)

In [18]:
A[2,:]

[7  8  9]

To access a column: we use ':' in place of the first index.

In [19]:
A[:,0]

⎡1⎤
⎢ ⎥
⎢4⎥
⎢ ⎥
⎣7⎦

There are countless otherways that we can manipulate, create, and change matrices. We will go over other techniques as we need them.

## Row Reduction

The procedure we know and love can now finally be automated and solved instantly! 

In [20]:
A = A = Matrix([[1, 2, 3, 12], [4, 5, 6, 13], [7,8,9, 14]])
A

⎡1  2  3  12⎤
⎢           ⎥
⎢4  5  6  13⎥
⎢           ⎥
⎣7  8  9  14⎦

In [21]:
R = A.rref()
R

⎛⎡1  0  -1  -34/3⎤        ⎞
⎜⎢               ⎥        ⎟
⎜⎢0  1  2   35/3 ⎥, (0, 1)⎟
⎜⎢               ⎥        ⎟
⎝⎣0  0  0     0  ⎦        ⎠

This returns the row reduced echelon form of the matrix. The following numbers in parentheses tells us the indices of the pivot columns. Recall indexing in Python starts with 0, so this tells us the 1st and 2nd columns are the pivot columns.

If you want just the row reduced matrix, then it is the first element of this new object.

In [22]:
R[0]

⎡1  0  -1  -34/3⎤
⎢               ⎥
⎢0  1  2   35/3 ⎥
⎢               ⎥
⎣0  0  0     0  ⎦

In this example, A was the entire augmented matrix corresponding to the system we wanted to solve. What if we wanted to solve a problem of the form:
$$ A \vec{x} = \vec{b} $$ 

In [23]:
A = Matrix([[1,1,-4],[1,-2,3],[3,-3,0]])
A

⎡1  1   -4⎤
⎢         ⎥
⎢1  -2  3 ⎥
⎢         ⎥
⎣3  -3  0 ⎦

In [24]:
b = Matrix([1,2,3])
b

⎡1⎤
⎢ ⎥
⎢2⎥
⎢ ⎥
⎣3⎦

In [25]:
AugmentedMatrix = A.col_insert(3, b) # insert b as the column number 3
AugmentedMatrix

⎡1  1   -4  1⎤
⎢            ⎥
⎢1  -2  3   2⎥
⎢            ⎥
⎣3  -3  0   3⎦

In [26]:
AugmentedMatrix.rref()

⎛⎡1  0  0  3⎤           ⎞
⎜⎢          ⎥           ⎟
⎜⎢0  1  0  2⎥, (0, 1, 2)⎟
⎜⎢          ⎥           ⎟
⎝⎣0  0  1  1⎦           ⎠

Now we can just read off the solution! 

### Errors involving Fractions

In [27]:
A = Matrix([[1, 3],[0.1, 0.3]])
A

⎡ 1    3 ⎤
⎢        ⎥
⎣0.1  0.3⎦

In [28]:
A.rref()

⎛⎡1  0⎤        ⎞
⎜⎢    ⎥, (0, 1)⎟
⎝⎣0  1⎦        ⎠

This result is certainly wrong! Row 2 is clearly a multiple of Row 1, so it should vanish in the row reduction.

In [29]:
A2 = Matrix([[1,3],[Rational(1,10),Rational(3,10)]])
A2

⎡ 1     3  ⎤
⎢          ⎥
⎣1/10  3/10⎦

In [30]:
A2.rref()

⎛⎡1  3⎤      ⎞
⎜⎢    ⎥, (0,)⎟
⎝⎣0  0⎦      ⎠

## Matrix Algebra

In [31]:
A = Matrix([[0, 1], [2, 3], [4,5]])
A

⎡0  1⎤
⎢    ⎥
⎢2  3⎥
⎢    ⎥
⎣4  5⎦

In [32]:
B = Matrix([[3, 2], [1, 0], [-1,2]])
B

⎡3   2⎤
⎢     ⎥
⎢1   0⎥
⎢     ⎥
⎣-1  2⎦

Addition of Matrices

In [33]:
A+B 

⎡3  3⎤
⎢    ⎥
⎢3  3⎥
⎢    ⎥
⎣3  7⎦

Scalar Multiplication

In [34]:
Rational(1, 2)*A

⎡0  1/2⎤
⎢      ⎥
⎢1  3/2⎥
⎢      ⎥
⎣2  5/2⎦

Transpose of a Matrix

In [35]:
A.T

⎡0  2  4⎤
⎢       ⎥
⎣1  3  5⎦

#### Matrix Multiplication

In [36]:
C = A*B.T # as simple as using the * operator
C

⎡2   0  2⎤
⎢        ⎥
⎢12  2  4⎥
⎢        ⎥
⎣22  4  6⎦

In [37]:
v = Matrix([-1, 2])
v

⎡-1⎤
⎢  ⎥
⎣2 ⎦

In [38]:
A*v

⎡2⎤
⎢ ⎥
⎢4⎥
⎢ ⎥
⎣6⎦

### Matrix Inverse

In [39]:
D = A.T*B
D

⎡-2  8 ⎤
⎢      ⎥
⎣1   12⎦

In [40]:
D.inv()

⎡-3/8  1/4 ⎤
⎢          ⎥
⎣1/32  1/16⎦

In [41]:
D*D.inv()

⎡1  0⎤
⎢    ⎥
⎣0  1⎦

Not every matrix has an inverse. For instance, the matrix we found earlier, C.

In [42]:
C

⎡2   0  2⎤
⎢        ⎥
⎢12  2  4⎥
⎢        ⎥
⎣22  4  6⎦

In [43]:
C.inv()

NonInvertibleMatrixError: Matrix det == 0; not invertible.

### Determinant

In [ ]:
C.det()

In [ ]:
D.det()

# Column, Null, and Row Space

In [44]:
A = Matrix([[1, 2, 3, 4],[5, 6, 7, 8], [4, 4, 4, 4]])
A

⎡1  2  3  4⎤
⎢          ⎥
⎢5  6  7  8⎥
⎢          ⎥
⎣4  4  4  4⎦

In [45]:
A.columnspace()

⎡⎡1⎤  ⎡2⎤⎤
⎢⎢ ⎥  ⎢ ⎥⎥
⎢⎢5⎥, ⎢6⎥⎥
⎢⎢ ⎥  ⎢ ⎥⎥
⎣⎣4⎦  ⎣4⎦⎦

In [46]:
A.nullspace()

⎡⎡1 ⎤  ⎡2 ⎤⎤
⎢⎢  ⎥  ⎢  ⎥⎥
⎢⎢-2⎥  ⎢-3⎥⎥
⎢⎢  ⎥, ⎢  ⎥⎥
⎢⎢1 ⎥  ⎢0 ⎥⎥
⎢⎢  ⎥  ⎢  ⎥⎥
⎣⎣0 ⎦  ⎣1 ⎦⎦

In [47]:
A.rowspace()

[[1  2  3  4], [0  -4  -8  -12]]